name: Generate Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate sitemap
      run: |
        cat > sitemap.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url><loc>https://omnitrends.github.io/</loc><lastmod>$(date -I)</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>
        </urlset>
        EOF
    
    - name: Commit sitemap
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git diff --staged --quiet || git commit -m "Update sitemap" && git push || echo "No changes to commit"