name: Update Sitemap

on:
  push:
    branches: [ main ]
    paths:
      - 'articles/**'
      - 'category/**'
      - 'pages/**'
      - 'json/**'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Generate sitemaps
      run: |
        cd python
        python sitemap_ultimate_generator.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml sitemap.txt robots.txt
        git diff --staged --quiet || git commit -m "Auto-update sitemaps [skip ci]"
        git push
